# Generated by Django 4.0.8 on 2022-12-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0002_empresa_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='foto',
        ),
    ]
