# Generated by Django 4.0.8 on 2022-12-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0003_remove_artista_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artista',
        ),
        migrations.AddField(
            model_name='artista',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artista.album'),
        ),
    ]
