# Generated by Django 4.0.8 on 2022-12-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0004_remove_album_artista_artista_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='album'),
        ),
    ]
