# Generated by Django 4.0.8 on 2022-12-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0005_album_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='portada',
        ),
    ]
